version: '3.8'

services:
  whatsapp-api:
    build: .
    container_name: whatsapp-api
    ports:
      - "3000:3000"
    volumes:
      - ./sessions:/app/sessions
      - ./logs:/app/logs
      - ./.env:/app/.env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s